### PR TITLE
Established applying dark theme as Chrome's PageAction

### PR DESCRIPTION
**Pull request by lekaha**
1. Default is the light mode.
2. Click PageAction to change theme(light/dark).

### CODE REVIEW

**Comment by jue58** [comment]
That's great. But I fail to reload the unpackaged extension. Apparently, the cause of failure is that "images/icon-16.png" does not exist.
Please remove the definition of the 16x16 icon from manifest.json or add a new 16x16 icon.

**Comment by lekaha** [comment]
Hey, I am sorry. I will fix it ASAP.

Rikiya Kawakami <notifications@github.com> 於 2016年2月9日 週二 10:22 寫道：

> That's great. But I fail to reload the unpackaged extension. Apparently,
> the cause of failure is that "images/icon-16.png" does not exist.
> Please remove the definition of the 16x16 icon from manifest.json or add a
> new 16x16 icon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jue58/typetalk-dark-theme/pull/1#issuecomment-181672812>
> .
>
-- 
Best Regards,
呂侃翰 Kan-Han Lu

**Comment by lekaha** [comment]
@jue58 I've fixed it. Please check it out and commit this pull request.

**Comment by jue58** [comment]
Looks good. Thanks!

**Pull request merged**
